const c=document.querySelector('#arena'),x=c.getContext('2d');
const $=s=>document.querySelector(s),ui={phase:$('#phaseText'),time:$('#timeText'),seed:$('#seedText'),tower:$('#towerText'),dir:$('#directionText'),aoe:$('#aoeText'),link:$('#linkText'),start:$('#startBtn'),restart:$('#restartBtn'),pause:$('#pauseBtn'),moveMode:$('#moveModeBtn'),assist:$('#assistToggle'),slow:$('#slowToggle'),towerSel:$('#towerSelect'),aoeSel:$('#aoeSelect'),panel:$('#resultPanel'),rk:$('#resultKicker'),rt:$('#resultTitle'),rr:$('#resultReason'),rp:$('#resultRestart')};
const map=new Image(),boss=new Image();map.src='./assets/M9S-MAP.png';boss.src='./assets/M9S-BOSS.png';
const cfg={inset:.166,size:.668,center:{x:2,y:2},tower:{A:{x:2,y:1,e:{x:2,y:0}},B:{x:3,y:2,e:{x:4,y:2}},C:{x:2,y:3,e:{x:2,y:4}},D:{x:1,y:2,e:{x:0,y:2}}},towerR:.38,playerR:.075,bossH:1.25,batR:.11,linkMax:1.5,waveDeg:22.5,batIron:.75,donutIn:.5,donutOut:2,bossIron:1,speed:1.28,waveHits:[10,13,16,19,22]};
const keys=new Set();let mode='keyboard',target=null,last=performance.now(),g=idle();
function idle(){return{status:'idle',paused:false,seed:0,t:0,phase:'待开始',tower:'A',dir:1,aoe:'iron',p:{x:2,y:3.35},bat:null,waves:new Set(),towerChecked:false,finalChecked:false}}
function rng(seed){return()=>{let t=seed+=0x6d2b79f5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function start(){let seed=Math.floor(Math.random()*0xffffffff),r=rng(seed),ts=['A','B','C','D'];let tower=ui.towerSel.value==='random'?ts[Math.floor(r()*4)]:ui.towerSel.value;let aoe=ui.aoeSel.value==='random'?(r()<.5?'iron':'donut'):ui.aoeSel.value;g=idle();Object.assign(g,{status:'running',seed,tower,dir:r()<.5?-1:1,aoe,p:startPos(tower)});target=null;ui.panel.classList.add('hidden')}
function startPos(t){let a=cfg.tower[t],v=norm({x:2-a.x,y:2-a.y});return{x:a.x+v.x*.18,y:a.y+v.y*.18}}
function upd(dt){if(g.status!=='running'||g.paused)return;dt*=ui.slow.checked?.55:1;g.t+=dt;move(dt);if(g.p.x<0||g.p.x>4||g.p.y<0||g.p.y>4)return fail('走出场地');phase();bat();towerHit();linkHit();waves();finalHit()}
function move(dt){if(mode==='click')return moveClick(dt);let vx=0,vy=0;if(keys.has('a')||keys.has('arrowleft'))vx--;if(keys.has('d')||keys.has('arrowright'))vx++;if(keys.has('w')||keys.has('arrowup'))vy--;if(keys.has('s')||keys.has('arrowdown'))vy++;if(!vx&&!vy)return;let l=Math.hypot(vx,vy),s=cfg.speed*dt/l;g.p.x+=vx*s;g.p.y+=vy*s}
function moveClick(dt){if(!target)return;let dx=target.x-g.p.x,dy=target.y-g.p.y,d=Math.hypot(dx,dy);if(d<.025){g.p.x=target.x;g.p.y=target.y;target=null;return}let s=Math.min(cfg.speed*dt,d);g.p.x+=dx/d*s;g.p.y+=dy/d*s}
function phase(){let t=g.t;g.phase=t<2?'准备':t<7?'踩分摊塔':t<10?'连线建立':t<22?'躲避水波':t<23?'最终 AoE 预警':'结算'}
function spawn(t){let a=cfg.tower[t];return{x:(a.x+a.e.x)/2,y:(a.y+a.e.y)/2}}
function bat(){if(g.t<7)return;let s=spawn(g.tower);if(!g.bat){g.bat={x:s.x,y:s.y,r:dist(s,cfg.center),a:Math.atan2(s.y-2,s.x-2)}}if(g.t<10){g.bat.x=s.x;g.bat.y=s.y;return}let p=Math.max(0,Math.min(1,(g.t-10)/12)),a=g.bat.a+g.dir*Math.PI*p;g.bat.x=2+Math.cos(a)*g.bat.r;g.bat.y=2+Math.sin(a)*g.bat.r}
function towerHit(){if(g.towerChecked||g.t<7)return;g.towerChecked=true;if(dist(g.p,cfg.tower[g.tower])>cfg.towerR)fail('分摊塔未踩中')}
function linkHit(){if(g.t<7||!g.bat||g.t>=23)return;if(dist(g.p,g.bat)>cfg.linkMax)fail('离连线蝙蝠太远')}
function waves(){for(let i=0;i<cfg.waveHits.length;i++){if(g.waves.has(i)||g.t<cfg.waveHits[i])continue;g.waves.add(i);if(inWave(g.p,i))return fail('踩中第 '+(i+1)+' 次八方扇形水波')}}
function finalHit(){if(g.finalChecked||g.t<23||!g.bat)return;g.finalChecked=true;if(dist(g.p,cfg.center)<=cfg.bossIron)return fail('被 Boss 钢铁击中');let d=dist(g.p,g.bat);if(g.aoe==='iron'&&d<=cfg.batIron)return fail('被蝙蝠钢铁击中');if(g.aoe==='donut'&&d>=cfg.donutIn&&d<=cfg.donutOut)return fail('被蝙蝠月环击中');done()}
function fail(r){if(g.status!=='running')return;g.status='failed';result(false,r)}function done(){if(g.status!=='running')return;g.status='success';result(true,'机制处理成功')}function result(ok,r){ui.rk.textContent=ok?'成功':'失败';ui.rt.textContent=ok?'机制成功':'机制失败';ui.rr.textContent=r;ui.panel.classList.remove('hidden')}
function inWave(p,i){let a=((Math.atan2(p.y-2,p.x-2)*180/Math.PI)%360+360)%360,sec=Math.floor(((a+11.25)%360)/22.5);return i%2?sec%2===1:sec%2===0}
function draw(){x.clearRect(0,0,c.width,c.height);if(map.complete&&map.naturalWidth)x.drawImage(map,0,0,c.width,c.height);else{x.fillStyle='#050507';x.fillRect(0,0,c.width,c.height)}guide();waveDraw();towerDraw();bossDraw();batDraw();targetDraw();playerDraw();finalDraw();hud()}
function guide(){if(!ui.assist.checked)return;let a=tc({x:0,y:0}),b=tc({x:4,y:4});x.strokeStyle='rgba(255,255,255,.25)';x.lineWidth=2;x.strokeRect(a.x,a.y,b.x-a.x,b.y-a.y)}
function towerDraw(){if(g.status==='idle'||g.t<2||g.t>=7)return;let p=tc(cfg.tower[g.tower]);x.fillStyle='rgba(255,74,133,.25)';x.strokeStyle='#ff5d98';x.lineWidth=5;x.beginPath();x.arc(p.x,p.y,u(cfg.towerR),0,Math.PI*2);x.fill();x.stroke();txt('分摊',p,30)}
function bossDraw(){let p=tc(cfg.center),h=u(cfg.bossH),w=h*(boss.naturalWidth||1)/(boss.naturalHeight||1);if(boss.complete&&boss.naturalWidth)x.drawImage(boss,p.x-w/2,p.y-h/2,w,h);else{circ(p,u(.18),'#15131d','#f14b87');txt('BOSS',p,18)}}
function batDraw(){if(!g.bat)return;let b=tc(g.bat),p=tc(g.p),d=dist(g.p,g.bat);x.strokeStyle=d<=cfg.linkMax?'rgba(255,71,135,.9)':'rgba(255,40,40,.95)';x.lineWidth=4;x.beginPath();x.moveTo(p.x,p.y);x.lineTo(b.x,b.y);x.stroke();if(ui.assist.checked){x.strokeStyle='rgba(255,255,255,.18)';x.lineWidth=2;x.beginPath();x.arc(b.x,b.y,u(cfg.linkMax),0,Math.PI*2);x.stroke()}circ(b,u(cfg.batR),'#22101d','#ff4b93');txt('蝠',b,17);if(g.t>=19){x.fillStyle='rgba(0,0,0,.72)';x.strokeStyle=g.aoe==='iron'?'#ff527f':'#5ecbff';round(b.x-34,b.y-u(.34),68,30,7);x.fill();x.stroke();txt(g.aoe==='iron'?'钢铁':'月环',{x:b.x,y:b.y-u(.34)+15},16)}}
function targetDraw(){if(mode!=='click'||!target)return;let p=tc(target);x.save();x.strokeStyle='rgba(69,214,255,.95)';x.lineWidth=3;x.beginPath();x.arc(p.x,p.y,u(.11),0,Math.PI*2);x.stroke();x.beginPath();x.moveTo(p.x-u(.16),p.y);x.lineTo(p.x+u(.16),p.y);x.moveTo(p.x,p.y-u(.16));x.lineTo(p.x,p.y+u(.16));x.stroke();x.restore()}
function playerDraw(){let p=tc(g.p);circ(p,u(cfg.playerR),'#f7f2ff','#45d6ff');txt('我',p,15,'#02131b')}
function waveDraw(){if(g.status==='idle'||g.t<7||g.t>22)return;let i=curWave();if(i<0)return;let o=u(2.9),cc=tc(cfg.center),half=Math.PI/16;x.fillStyle='rgba(74,160,255,.26)';x.strokeStyle='rgba(90,190,255,.74)';x.lineWidth=2;for(let s=0;s<16;s++){let danger=i%2?s%2===1:s%2===0;if(!danger)continue;let m=s*Math.PI/8;x.beginPath();x.moveTo(cc.x,cc.y);x.arc(cc.x,cc.y,o,m-half,m+half);x.closePath();x.fill();x.stroke()}}
function curWave(){for(let i=0;i<cfg.waveHits.length;i++){let st=i?cfg.waveHits[i-1]:7;if(g.t>=st&&g.t<=cfg.waveHits[i])return i}return-1}
function finalDraw(){if(!g.bat||g.t<22)return;let a=g.t<23?.28:.18,b=tc(g.bat),bo=tc(cfg.center);x.fillStyle='rgba(255,67,112,'+a+')';x.strokeStyle='rgba(255,91,137,.9)';x.lineWidth=4;x.beginPath();x.arc(bo.x,bo.y,u(cfg.bossIron),0,Math.PI*2);x.fill();x.stroke();if(g.aoe==='iron'){x.beginPath();x.arc(b.x,b.y,u(cfg.batIron),0,Math.PI*2);x.fill();x.stroke()}else{x.fillStyle='rgba(75,192,255,'+a+')';x.strokeStyle='rgba(112,213,255,.95)';let outer=u(cfg.donutOut),inner=u(cfg.donutIn);x.beginPath();x.arc(b.x,b.y,outer,0,Math.PI*2);x.moveTo(b.x+inner,b.y);x.arc(b.x,b.y,inner,0,Math.PI*2,true);x.fill('evenodd');x.beginPath();x.arc(b.x,b.y,outer,0,Math.PI*2);x.stroke();x.beginPath();x.arc(b.x,b.y,inner,0,Math.PI*2);x.stroke()}}
function hud(){ui.phase.textContent=g.phase;ui.time.textContent=g.t.toFixed(1)+'s';ui.seed.textContent=g.seed||'-';ui.tower.textContent=g.status==='idle'?'-':g.tower;ui.dir.textContent=g.status==='idle'?'-':g.dir>0?'顺时针':'逆时针';ui.aoe.textContent=g.status==='idle'?'-':g.aoe==='iron'?'钢铁':'月环';ui.link.textContent=g.bat?dist(g.p,g.bat).toFixed(2)+' / '+cfg.linkMax:'-';ui.pause.textContent=g.paused?'继续':'暂停';ui.moveMode.textContent=mode==='keyboard'?'移动方式：WASD':'移动方式：点击'}
function tc(p){let ins=c.width*cfg.inset,sz=c.width*cfg.size;return{x:ins+p.x/4*sz,y:ins+p.y/4*sz}}function fromEvent(e){let r=c.getBoundingClientRect(),px=(e.clientX-r.left)*c.width/r.width,py=(e.clientY-r.top)*c.height/r.height,ins=c.width*cfg.inset,sz=c.width*cfg.size;return{x:(px-ins)/sz*4,y:(py-ins)/sz*4}}function u(v){return c.width*cfg.size*v/4}function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function norm(v){let l=Math.hypot(v.x,v.y)||1;return{x:v.x/l,y:v.y/l}}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function circ(p,r,f,s){x.fillStyle=f;x.strokeStyle=s;x.lineWidth=4;x.beginPath();x.arc(p.x,p.y,r,0,Math.PI*2);x.fill();x.stroke()}function txt(t,p,fs,col='#fff'){x.fillStyle=col;x.font='700 '+fs+'px Inter,sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText(t,p.x,p.y)}function round(a,b,w,h,r){x.beginPath();x.moveTo(a+r,b);x.arcTo(a+w,b,a+w,b+h,r);x.arcTo(a+w,b+h,a,b+h,r);x.arcTo(a,b+h,a,b,r);x.arcTo(a,b,a+w,b,r);x.closePath()}
function frame(n){let dt=Math.min((n-last)/1000,.05);last=n;upd(dt);draw();requestAnimationFrame(frame)}
window.addEventListener('keydown',e=>{let k=e.key.toLowerCase();if(['arrowleft','arrowright','arrowup','arrowdown','w','a','s','d',' '].includes(k))e.preventDefault();if(k===' '){g.paused=!g.paused;return}keys.add(k)});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));ui.start.onclick=start;ui.restart.onclick=start;ui.rp.onclick=start;ui.pause.onclick=()=>{if(g.status==='running')g.paused=!g.paused};ui.moveMode.onclick=()=>{mode=mode==='keyboard'?'click':'keyboard';target=null;hud()};c.addEventListener('pointerdown',e=>{if(mode!=='click'||g.status!=='running'||g.paused)return;e.preventDefault();let p=fromEvent(e);target={x:clamp(p.x,0,4),y:clamp(p.y,0,4)}});map.onload=draw;boss.onload=draw;requestAnimationFrame(frame);
